projects:
  "DSMFramework": "juanmuscaria"
  "Crucible": "cruciblemc"
  "javactl": "juanmuscaria"
  "NotSoLegacyWorkspace-Gradle-Groovy": "juanmuscaria"
  "blockheads-patch": "juanmuscaria"
  "uncode": "juanmuscaria"