projects:
  "DSMFramework": "juanmuscaria"
  "Crucible": "cruciblemc"
  "javactl": "juanmuscaria"
  "NotSoLegacyWorkspace-Gradle-Groovy": "juanmuscaria"
  "blockheads-patch": "juanmuscaria"
  "uncode": "juanmuscaria"
  "microcord": "juanmuscaria"
  # note about dots, put them in []
  "[.github]": "AutoArchives"
  "PraesidiumEvolutionis": "cruciblemc"